apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: payment-resource-k8s-deployment
spec:
  selector:
    matchLabels:
      app: payment-resource
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: payment-resource
    spec:
      containers:
        - name: payment-resource
          image: nazeer78/payment-image:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
              protocol: TCP

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: payment-resourcesvc
spec:
  type: NodePort # type of the service.
  selector:
    app: payment-resource
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
